nodeLinker: node-modules

packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": "*"
